# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@master
      with:
        url: 'https://www.reddit.com/r/AskReddit/.json'
        method: 'GET'
    - name: Show Response
      run: echo 'comment'
    - name: Show github
      run: echo ${{ secrets.GITHUB_TOKEN }}
    - name: Check endpoint status
      uses: gayanvoice/javascript-action@1
      with:
        milliseconds: 5000
    - name: Create directory
      run: mkdir history 
